language: node_js
node_js:
  - 6
  - 8
sudo: false
cache:
  directories:
    - node_modules
script:
  # Run test script
  - "npm run lint"
  - "npm test -- --maxWorkers=4"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
